import { TextoLocalizado } from '../../shared/idioma.service';

export interface Projeto {
  titulo: TextoLocalizado;
  descricao: TextoLocalizado;
  urlImagem: string;
  urlRepositorio: string;
  tecnologias: string[];
}
const projeto = (
  tituloPt: string,
  tituloEn: string,
  descricaoPt: string,
  descricaoEn: string,
  urlRepositorio: string,
  tecnologias: string[],
  urlImagem = '',
): Projeto => ({
  titulo: { pt: tituloPt, en: tituloEn },
  descricao: { pt: descricaoPt, en: descricaoEn },
  urlImagem,
  urlRepositorio,
  tecnologias,
});

export const textosProjetos = {
  pt: {
    titulo: 'Projetos',
    introducao:
      'Nesta seção, apresento projetos que refletem minha experiência e minhas habilidades como desenvolvedor. Cada item reúne uma descrição detalhada, as tecnologias utilizadas e os links para visualizar a imagem do projeto ou acessar o código-fonte.',
    tecnologias: 'Tecnologias utilizadas',
    imagem: 'Ver imagem',
    repositorio: 'Repositório',
    fechar: 'Fechar',
  },
  en: {
    titulo: 'Projects',
    introducao:
      'This section presents projects that reflect my experience and skills as a developer. Each entry includes a detailed description, the technologies used, and links to view project media or access the source code.',
    tecnologias: 'Technologies used',
    imagem: 'View image',
    repositorio: 'Repository',
    fechar: 'Close',
  },
};

export const projetos: Projeto[] = [
  projeto(
    'OCR Bancário',
    'Banking OCR',
    'Protótipo voltado à leitura e à estruturação de informações bancárias a partir de documentos digitalizados, explorando automação e tratamento de dados.',
    'Prototype for reading and structuring banking information from digitized documents, exploring automation and data processing.',
    'https://github.com/DrElucidator/OCRBancario',
    ['C#', '.NET'],
  ),
  projeto(
    'Gerador de Certificados Online',
    'Online Certificate Generator',
    'A aplicação permite cadastrar cursos e alunos, gerar certificados em lote de forma assíncrona e acompanhar o processamento dos certificados.',
    'Registers courses and students, generates certificates asynchronously in batches, and tracks their processing.',
    'https://github.com/WriteLine-GreenLife-Devs/gerador-de-certificados',
    [
      'C#',
      '.NET 10',
      'Entity Framework',
      'ASP.NET Core',
      'MassTransit',
      'RabbitMQ',
      'SQL Server',
      'JWT',
    ],
  ),
  projeto(
    'Delivery App',
    'Delivery App',
    'A API REST gerencia clientes, estabelecimentos e cardápios de uma plataforma de pedidos e entregas.',
    'REST API for customers, restaurants, menus, products, and delivery ordering workflows.',
    'https://github.com/DrElucidator/delivery-app',
    [
      'C#',
      '.NET 10',
      'Entity Framework',
      'ASP.NET Core',
      'MassTransit',
      'RabbitMQ',
      'PostgreSQL',
      'JWT',
    ],
  ),
  projeto(
    'e-Agenda API',
    'e-Agenda API',
    'API de agenda para centralizar contatos, compromissos, tarefas e despesas em uma solução organizada por módulos.',
    'Scheduling API that centralizes contacts, appointments, tasks, and expenses in modular services.',
    'https://github.com/WriteLine-GreenLife-Devs/e-agenda-api',
    ['C#', '.NET', 'ASP.NET Core', 'Web API'],
  ),
  projeto(
    'Data Humanizada',
    'Humanized Date',
    'Biblioteca utilitária para converter datas e intervalos de tempo em representações mais legíveis e próximas da linguagem natural.',
    'Utility library that turns dates and time intervals into more readable, natural-language representations.',
    'https://github.com/DrElucidator/data-humanizada',
    ['C#', '.NET'],
  ),
  projeto(
    'Controle de Bar',
    'Bar Management System',
    'Sistema web multi-tenant para gerenciamento de bares, com controle de mesas, garçons, produtos, contas e pedidos.',
    'Multi-tenant web system for bar management, covering tables, servers, products, bills, and orders.',
    'https://github.com/WriteLine-GreenLife-Devs/controle-de-bar-2026',
    [
      'C#',
      '.NET 10',
      'ASP.NET Core MVC',
      'Entity Framework Core',
      'SQL Server',
      'ASP.NET Core Identity',
      'Bootstrap',
      'MSTest',
      'Playwright',
      'Azure',
    ],
    '/img/projects/controle-de-bar/controle-de-bar.gif',
  ),
  projeto(
    'Gerador de Provas',
    'Test Generator',
    'A aplicação organiza disciplinas, matérias e questões para permitir a criação de testes personalizados.',
    'Organizes subjects and questions to create customized tests, including random selection and PDF export.',
    'https://github.com/WriteLine-GreenLife-Devs/gerador-de-provas-2026',
    ['HTML', 'CSS', 'C#', '.NET 10', 'Entity Framework'],
  ),
  projeto(
    'Escola de Cursos',
    'Course School',
    'Sistema web para administrar as operações de uma escola de cursos, incluindo cadastros e processos relacionados à rotina acadêmica.',
    'Web system for managing course-school operations, registrations, and academic routines.',
    'https://github.com/WriteLine-GreenLife-Devs/EscolaDeCursos',
    ['C#', '.NET', 'ASP.NET Core MVC', 'Entity Framework Core', 'SQL Server', 'Bootstrap'],
  ),
  projeto(
    'Escola de Cursos',
    'Course School',
    'Aplicação web dedicada ao gerenciamento de uma escola de cursos, desenvolvida como evolução prática de fluxos de cadastro e administração acadêmica.',
    'Web application for managing a course school, developed as a practical evolution of registration and academic administration flows.',
    'https://github.com/DrElucidator/escola-de-cursos-2026',
    ['HTML', 'CSS', 'JavaScript'],
  ),
  projeto(
    'e-Agenda Web',
    'e-Agenda Web',
    'Aplicação web para organização pessoal e profissional, com módulos de contatos, compromissos, tarefas, despesas e categorias.',
    'Web application for personal and professional organization, with contacts, appointments, tasks, expenses, and categories.',
    'https://github.com/WriteLine-GreenLife-Devs/e-Agenda-Web',
    ['C#', 'ASP.NET Core MVC', 'Dapper', 'SQL Server', 'Bootstrap', 'Azure'],
  ),
  projeto(
    'Conversor de Números Romanos',
    'Roman Numeral Converter',
    'Utilitário que converte números inteiros em algarismos romanos, aplicando as regras de composição e subtração da numeração romana.',
    'Utility that converts integers into Roman numerals using composition and subtraction rules.',
    'https://github.com/DrElucidator/Conversor-de-numeros-inteiros-para-romanos',
    ['C#', '.NET'],
  ),
  projeto(
    'Controle de Medicamentos Web',
    'Medication Management Web',
    'Sistema web para administrar medicamentos e estoque hospitalar, com cadastros de pacientes, fornecedores e funcionários.',
    'Web system for managing medications and hospital inventory, including patients, suppliers, and staff.',
    'https://github.com/WriteLine-GreenLife-Devs/Controle-de-Medicamentos-Web',
    ['C#', 'ASP.NET Core MVC', 'Entity Framework Core', 'SQL Server', 'Bootstrap'],
  ),
  projeto(
    'Lista de Compras Web',
    'Shopping List Web',
    'Aplicação web para criar e acompanhar listas de compras, praticando operações de cadastro, edição e organização de itens.',
    'Web application to create and track shopping lists, covering item registration, editing, and organization.',
    'https://github.com/WriteLine-GreenLife-Devs/Lista-de-Compras-Web',
    ['C#', 'ASP.NET Core MVC', 'Entity Framework Core', 'SQL Server', 'Bootstrap'],
  ),
  projeto(
    'Clube da Leitura Web',
    'Reading Club Web',
    'Aplicação web para gerenciamento de um clube da leitura, reunindo os cadastros e operações necessários para sua organização.',
    'Web application for managing a reading club and its registration and operational workflows.',
    'https://github.com/WriteLine-GreenLife-Devs/Clube-da-Leitura-Web',
    ['C#', 'ASP.NET Core MVC', 'Entity Framework Core', 'SQL Server', 'Bootstrap'],
  ),
  projeto(
    'Cheque por Extenso',
    'Check Amount in Words',
    'Desafio de lógica que converte valores monetários em sua representação textual por extenso, considerando reais e centavos.',
    'Logic challenge that converts monetary amounts into written text, accounting for reais and cents.',
    'https://github.com/DrElucidator/Cheque-por-extenso',
    ['C#', '.NET'],
  ),
  projeto(
    'Gestão de Equipamentos Web',
    'Equipment Management Web',
    'Sistema web para controlar fabricantes, equipamentos e chamados de manutenção, substituindo processos manuais de inventário.',
    'Web system for managing manufacturers, equipment, and maintenance requests, replacing manual inventory processes.',
    'https://github.com/DrElucidator/gestao-de-equipamentos-web-2026',
    ['C#', 'ASP.NET Core MVC', 'Entity Framework Core', 'SQL Server', 'Bootstrap'],
  ),
  projeto(
    'Controle de Medicamentos',
    'Medication Management',
    'Aplicação para controle de medicamentos, estoque e operações relacionadas ao contexto hospitalar.',
    'Application for medication, inventory, and hospital-related operations management.',
    'https://github.com/WriteLine-GreenLife-Devs/Controle-de-Medicamentos',
    ['C#', '.NET'],
  ),
  projeto(
    'Lista de Compras',
    'Shopping List',
    'Aplicação para registrar e organizar itens de uma lista de compras, exercitando operações fundamentais de persistência e negócio.',
    'Application for registering and organizing shopping-list items while practicing persistence and business operations.',
    'https://github.com/DrElucidator/Lista-de-Compras',
    ['C#', '.NET'],
  ),
  projeto(
    'Clube da Leitura',
    'Reading Club',
    'Sistema para organizar as informações e operações de um clube da leitura em uma aplicação de domínio estruturado.',
    'System for organizing reading-club information and operations in a structured domain application.',
    'https://github.com/DrElucidator/clube-da-leitura-2026',
    ['C#', '.NET'],
  ),
  projeto(
    'Gestão de Equipamentos',
    'Equipment Management',
    'Aplicação para cadastrar equipamentos e acompanhar chamados de manutenção, modelando um fluxo básico de inventário.',
    'Application for registering equipment and tracking maintenance requests through a basic inventory workflow.',
    'https://github.com/DrElucidator/gestao-de-equipamentos-2026',
    ['C#', '.NET'],
  ),
  projeto(
    'Atividades de Orientação a Objetos',
    'Object-Oriented Programming Activities',
    'Conjunto de exercícios de orientação a objetos em C#, explorando modelagem de classes, encapsulamento e relações entre entidades.',
    'C# object-oriented programming exercises covering class modeling, encapsulation, and entity relationships.',
    'https://github.com/DrElucidator/Atividades-de-orientacao-a-objetos-csharp',
    ['C#', '.NET', 'Object-Oriented Programming'],
  ),
  projeto(
    'Sistema Bancário de Conta Corrente',
    'Current Account Banking System',
    'Simulação de operações de conta corrente, com regras de negócio para movimentações, saldo e gerenciamento de contas.',
    'Simulation of current-account operations, with business rules for transactions, balances, and account management.',
    'https://github.com/DrElucidator/Sistema-Bancario-de-Conta-Corrente',
    ['C#', '.NET', 'Object-Oriented Programming'],
  ),
  projeto(
    'Termo',
    'Termo',
    'Implementação de um jogo de adivinhação de palavras inspirado em Termo, trabalhando regras de tentativa e comparação de caracteres.',
    'Word-guessing game inspired by Termo, focused on attempt rules and character comparison.',
    'https://github.com/DrElucidator/Termo',
    ['C#', '.NET'],
  ),
  projeto(
    'Janken',
    'Janken',
    'Jogo de pedra, papel e tesoura desenvolvido para praticar condicionais, aleatoriedade e interação em console.',
    'Rock-paper-scissors game developed to practice conditionals, randomness, and console interaction.',
    'https://github.com/DrElucidator/Janken',
    ['C#', '.NET'],
  ),
  projeto(
    'Gerador de Losango',
    'Diamond Generator',
    'Exercício de lógica para gerar losangos no console, trabalhando laços, alinhamento e construção de padrões.',
    'Logic exercise that generates diamonds in the console, practicing loops, alignment, and patterns.',
    'https://github.com/DrElucidator/Gerador-de-Losango',
    ['C#', '.NET'],
  ),
  projeto(
    'Tupiniquim',
    'Tupiniquim',
    'Projeto de lógica em C# desenvolvido para praticar fluxo de execução, regras e interação em aplicações de console.',
    'C# logic project for practicing execution flow, rules, and console interaction.',
    'https://github.com/DrElucidator/Tupiniquim',
    ['C#', '.NET'],
  ),
  projeto(
    'Jogo dos Dados',
    'Dice Game',
    'Jogo de console baseado em lançamentos de dados, explorando aleatoriedade, pontuação e regras de rodada.',
    'Console dice game exploring randomness, scoring, and round rules.',
    'https://github.com/DrElucidator/Jogo-dos-Dados',
    ['C#', '.NET'],
  ),
  projeto(
    'Jogo da Forca',
    'Hangman',
    'Versão em console do jogo da forca, com controle de tentativas, letras utilizadas e progresso da palavra.',
    'Console version of Hangman with attempt tracking, used letters, and word progress.',
    'https://github.com/DrElucidator/Jogo-da-Forca',
    ['C#', '.NET'],
  ),
  projeto(
    'Práticas Iniciais em C#',
    'Introductory C# Practice',
    'Coleção de exercícios iniciais para consolidar sintaxe, variáveis, operadores, estruturas condicionais e laços em C#.',
    'Collection of introductory exercises covering C# syntax, variables, operators, conditionals, and loops.',
    'https://github.com/DrElucidator/Atividades-de-Praticas-Iniciais-em-CSharp',
    ['C#', '.NET'],
  ),
  projeto(
    'Jogo de Adivinhação',
    'Guessing Game',
    'Jogo de console em que o jogador tenta descobrir um número sorteado, praticando entrada de dados, condições e tentativas.',
    'Console game in which the player guesses a random number, practicing input, conditions, and attempts.',
    'https://github.com/DrElucidator/Jogo-de-Adivinhacao',
    ['C#', '.NET'],
  ),
  projeto(
    'Calculadora',
    'Calculator',
    'Calculadora de console para operações aritméticas básicas, criada como exercício de fundamentos de programação.',
    'Console calculator for basic arithmetic operations, created as a programming-fundamentals exercise.',
    'https://github.com/DrElucidator/Calculadora-C-',
    ['C#', '.NET'],
  ),
  projeto(
    'Hello World',
    'Hello World',
    'Primeiro projeto em C#, registrando o início da trajetória de estudos com uma aplicação de console.',
    'First C# project, marking the beginning of a learning journey through a console application.',
    'https://github.com/DrElucidator/HelloWorld',
    ['C#', '.NET'],
  ),
];
